### ISSUE TITLE
Watchface versus app?

### ISSUE THREAD

**Issue by osresearch** [dakhnod/Fossil-HR-SDK#18]
Right now I'm building my watchface as `stopwatchApp` so that it shows up in the menu. What should it be named to be the main watchface? Are there any things that need to be specifically implemented to support opening the app menu or handling notifications?

**Comment by arjan-s** [comment]
The name doesn't matter, it's the first digit of the value we call "version" that defines whether the watch sees it as an app or a watchface. See for instance [this comment](https://github.com/dakhnod/Fossil-HR-SDK/issues/13#issuecomment-1220849588).

There are some things (events mainly) you need to implement to get a fully working watchface, take a look at [our watchface code](https://codeberg.org/Freeyourgadget/fossil-hr-watchface/src/branch/main/open_source_watchface.js) for inspiration.

**Comment by sebo-b** [comment]
Hi, it is quite an old thread - but I spent at least an hour to finally figure it out.

So first of all there is an inconsistency between Gadgetbridge and the fossil watch in detecting what's App vs Watchface.

For the watch, it seems that the version number is what matters. If the version starts with `1.` it is a watch face and will be launched immediately after the upload, otherwise, it is an app.

Gadgetbridge ignores that, and if the file with compiled code (output from `jerryscript-snaphot`) doesn't end with `App`, it is shown in the `Installed Watchfaces` section, even if it is not a watch face. And vice-versa, if it ends with `App`, even if it is a watch face and is launched automatically, Gadgetbride will list it under the `Installed apps` section.

Hope it helps.
